
name: DAST Baseline Scans

on:
  #push:
  workflow_dispatch: # to allow to run manually




jobs:

  DAST-Baseline-Scan:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'temurin'

      - name: Setup Maven Dependency Cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Deploy Marathon for Local Integration Tests
        run: cd integration && ./start-integration.sh

      # https://github.com/marketplace/actions/owasp-zap-baseline-scan
      # https://www.zaproxy.org/docs/docker/baseline-scan/
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.13.0
        with:
          target: 'http://localhost:9090/marathon'
          # rules_file_name: '.zap/rules.tsv'
          # cmd_options: '-a'



